name: ChainCongruency
channels:
    - defaults
    - conda-forge
    - damianavila82
dependencies:
    - python=3.6.3
    - numpy
    - scipy
    - pandas
    - matplotlib
    - widgetsnbextension
    - jupyter_contrib_nbextensions
    - rise
