  int counter = 0;
  string f_name_first_total = "";
  string f_name_first_Dubna = "";
  string f_name_first_Lund = "";
  string f_name_first_BGS = "";
  string f_name_second_total = "";
  string f_name_second_Lund = "";
  string f_name_second_Dubna = "";
  string f_name_second_BGS = "";
  string f_name_third_total = "";
  string f_name_fourth_total = "";
  string f_name_fifth_total = "";
  string f_name_sixth_total = "";
  string f_name_seventh_total = "";
  /* TF1 *first[allowed_nr_of_chains];
  TF1 *second[allowed_nr_of_chains];
  TF1 *third[allowed_nr_of_chains];
  TF1 *fourth[allowed_nr_of_chains];
  TF1 *fifth[allowed_nr_of_chains];
  TF1 *sixth[allowed_nr_of_chains];
  TF1 *seventh[allowed_nr_of_chains];*/
  TF1 *pic1;
  TF1 *pic2;
  TF1 *pic3;
